spring:
  application:
    name: orderservice
wxshop:
  orderservice:
    version: 1.0.0

dubbo:
  scan:
    base-packages: com.oak.wxshop.orderservice

  protocol:
    name: dubbo
    port: -1

  ## Dubbo Registry
  registry:
    address: zookeeper://127.0.0.1:2181
